### ISSUE TITLE
Error Message

### ISSUE THREAD

**Issue by basharald** [richardlawley/EntityFrameworkAttributeConfig#1]
How Can i Add Error Message to CDecimalPrecisionAttribute?!

**Comment by richardlawley** [comment]
What are you trying to achieve?  Please include a sample of what you want to do.

**Comment by basharald** [comment]
I am trying to add a new filed to my model for example:

 [CDecimalPrecisionAttribute(8, 2)]
  public decimal Profit { get; set; }

and i want to add ErrorMessage to the field to be like:

[CDecimalPrecisionAttribute(8, 2,ErrorMessage="error not decimal")]
  public decimal Profit { get; set; }

As i noticed that CDecimalPrecisionAttribute class inherits from Attribute not from ValidationAttribute

So is there any solution to add the error message in my model directly ?
thank you.

**Comment by richardlawley** [comment]
This project is nothing to do with validation, it's about configuring Entity Framework fields through attributes.
